# Generated by Django 5.2.17 on 2026-09-14 14:54

import uuid

import django.db.models.deletion
import django.db.models.lookups
from django.db import migrations, models

import aegis_apps.catalog.domain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_name', models.BinaryField(max_length=255)),
                ('display_name', models.TextField()),
                ('name_key', models.BinaryField(max_length=2048)),
                ('logical_name', models.TextField(null=True)),
                ('kind', models.CharField(choices=[('directory', 'directory'), ('file', 'file'), ('symlink', 'symlink'), ('special', 'special')], max_length=16)),
                ('type_hint', models.CharField(max_length=16, null=True)),
                ('source_state', models.CharField(choices=[('present', 'present'), ('missing', 'missing'), ('inaccessible', 'inaccessible'), ('unsupported', 'unsupported')], default=aegis_apps.catalog.domain.SourceState['PRESENT'], max_length=16)),
                ('size', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('mtime_ns', models.DecimalField(decimal_places=0, max_digits=30, null=True)),
                ('ctime_ns', models.DecimalField(decimal_places=0, max_digits=30, null=True)),
                ('device', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('inode', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('source_revision', models.PositiveBigIntegerField(default=0)),
                ('catalog_version', models.PositiveBigIntegerField(default=0)),
                ('children_version', models.PositiveBigIntegerField(default=0)),
                ('observation_epoch', models.PositiveBigIntegerField(default=0)),
                ('seen_generation', models.PositiveBigIntegerField(default=0)),
                ('seen_attempt', models.PositiveBigIntegerField(default=0)),
                ('observed_at', models.DateTimeField(null=True)),
                ('logical_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logical_children', to='catalog.catalogentry')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roots.root')),
                ('source_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_children', to='catalog.catalogentry')),
            ],
            options={
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(fields=('root', 'id'), name='catalog_root_id_uniq'), models.UniqueConstraint(condition=models.Q(('source_parent__isnull', True)), fields=('root',), name='catalog_one_anchor_per_root'), models.UniqueConstraint(condition=models.Q(('source_parent__isnull', False)), fields=('root', 'source_parent', 'raw_name'), name='catalog_source_location_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('kind', aegis_apps.catalog.domain.EntryKind['DIRECTORY']), ('raw_name', b''), ('source_parent__isnull', True)), models.Q(('source_parent__isnull', False), django.db.models.lookups.GreaterThan(models.Func('raw_name', function='octet_length', output_field=models.IntegerField()), 0)), _connector='OR'), name='catalog_anchor_or_child'), models.CheckConstraint(condition=models.Q(django.db.models.lookups.LessThanOrEqual(models.Func('raw_name', function='octet_length', output_field=models.IntegerField()), 255), models.Q(('raw_name__in', (b'.', b'..')), _negated=True), django.db.models.lookups.Exact(models.Func('raw_name', output_field=models.IntegerField(), template="position(decode('00', 'hex') in %(expressions)s)"), 0), django.db.models.lookups.Exact(models.Func('raw_name', output_field=models.IntegerField(), template="position(decode('2f', 'hex') in %(expressions)s)"), 0)), name='catalog_raw_name_valid'), models.CheckConstraint(condition=django.db.models.lookups.LessThanOrEqual(models.Func('name_key', function='octet_length', output_field=models.IntegerField()), 2048), name='catalog_name_key_bounded'), models.CheckConstraint(condition=models.Q(('kind__in', ('directory', 'file', 'symlink', 'special'))), name='catalog_kind_valid'), models.CheckConstraint(condition=models.Q(('source_state__in', ('present', 'missing', 'inaccessible', 'unsupported'))), name='catalog_source_state_valid'), models.CheckConstraint(condition=models.Q(('source_parent', models.F('id')), _negated=True), name='catalog_source_not_self'), models.CheckConstraint(condition=models.Q(('logical_parent', models.F('id')), _negated=True), name='catalog_logical_not_self'), models.CheckConstraint(condition=models.Q(('size__gte', 0)), name='catalog_size_nonnegative'), models.CheckConstraint(condition=models.Q(('device__gte', 0)), name='catalog_device_nonnegative'), models.CheckConstraint(condition=models.Q(('inode__gte', 0)), name='catalog_inode_nonnegative')],
            },
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE catalog_catalogentry
                    ADD CONSTRAINT catalog_source_parent_same_root
                    FOREIGN KEY (root_id, source_parent_id)
                    REFERENCES catalog_catalogentry (root_id, id)
                    ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED,
                    ADD CONSTRAINT catalog_logical_parent_same_root
                    FOREIGN KEY (root_id, logical_parent_id)
                    REFERENCES catalog_catalogentry (root_id, id)
                    ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
                ALTER TABLE catalog_catalogentry
                    DROP CONSTRAINT catalog_source_parent_same_root,
                    DROP CONSTRAINT catalog_logical_parent_same_root;
            """,
        ),
    ]
