#define _POSIX_C_SOURCE 200809L
#include <aegis/modules/aide.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define AIDE_CONF      "/etc/aide.conf"
#define AIDE_DB_NEW    "/var/lib/aide/aide.db.new.gz"
#define AIDE_DB        "/var/lib/aide/aide.db.gz"

static const char *DEFAULT_AIDE_CONF =
    "# Generated by aegis\n"
    "database=file:" AIDE_DB "\n"
    "database_out=file:" AIDE_DB_NEW "\n"
    "gzip_dbout=yes\n"
    "report_url=file:/var/log/aide/aide.log\n"
    "report_url=stdout\n"
    "verbose=5\n"
    "\n"
    "# Default rules\n"
    "All = p+i+n+u+g+s+m+S+sha256+acl+xattrs+selinux\n"
    "\n"
    "# Directories to check\n"
    "/boot   All\n"
    "/etc    All\n"
    "/bin    All\n"
    "/sbin   All\n"
    "/lib    All\n"
    "/lib64  All\n"
    "/usr    All\n"
    "\n"
    "!/proc\n"
    "!/sys\n"
    "!/dev\n"
    "!/run\n"
    "!/tmp\n"
    "!/var/tmp\n"
    "!/var/log\n";

aegis_result_t aegis_aide_apply(const void *config, aegis_executor_t *exec) {
    const aegis_aide_config_t *cfg = config;
    if (!cfg || !cfg->enabled)
        return aegis_result_skip("aide: disabled");

    aegis_result_t res = aegis_result_ok("aide: applied");

    /* Install aide */
    const char *install[] = {"pacman", "-S", "--noconfirm", "--needed", "aide", NULL};
    aegis_exec_result_t r = exec->execute_sudo(install, exec->ctx);
    if (r.exit_code != 0) {
        aegis_result_free(&res);
        aegis_exec_result_free(&r);
        return aegis_result_fail("aide: pacman -S failed");
    }
    aegis_exec_result_free(&r);
    aegis_result_add_action(&res, "Ensured aide package installed");

    /* Write default aide.conf */
    if (exec->write_file(AIDE_CONF, DEFAULT_AIDE_CONF, true, exec->ctx) != 0) {
        aegis_result_free(&res);
        return aegis_result_fail("aide: failed to write " AIDE_CONF);
    }
    aegis_result_add_action(&res, "Wrote default " AIDE_CONF);

    /* Initialize database */
    const char *init_argv[] = {"aide", "--init", NULL};
    r = exec->execute_sudo(init_argv, exec->ctx);
    if (r.exit_code != 0) {
        aegis_result_free(&res);
        aegis_exec_result_free(&r);
        return aegis_result_fail("aide: aide --init failed");
    }
    aegis_exec_result_free(&r);
    aegis_result_add_action(&res, "Initialized aide database with --init");

    /* Copy new db to expected location */
    const char *cp_argv[] = {"cp", AIDE_DB_NEW, AIDE_DB, NULL};
    r = exec->execute_sudo(cp_argv, exec->ctx);
    if (r.exit_code != 0) {
        aegis_result_free(&res);
        aegis_exec_result_free(&r);
        return aegis_result_fail("aide: cp database failed");
    }
    aegis_exec_result_free(&r);
    aegis_result_add_action(&res, "Copied " AIDE_DB_NEW " to " AIDE_DB);

    return res;
}

aegis_result_t aegis_aide_status(aegis_executor_t *exec) {
    bool db_exists = exec->file_exists(AIDE_DB, exec->ctx);

    char msg[128];
    snprintf(msg, sizeof(msg), "aide: database=%s", db_exists ? "present" : "missing");
    if (db_exists) return aegis_result_ok(msg);
    return aegis_result_fail(msg);
}

aegis_result_t aegis_aide_verify(aegis_executor_t *exec) {
    bool db_exists = exec->file_exists(AIDE_DB, exec->ctx);
    if (!db_exists) return aegis_result_fail("aide: database missing, run apply first");

    const char *argv[] = {"aide", "--check", NULL};
    aegis_exec_result_t r = exec->execute_sudo(argv, exec->ctx);
    int exit_code = r.exit_code;
    aegis_exec_result_free(&r);

    char msg[128];
    snprintf(msg, sizeof(msg), "aide: check exit_code=%d%s",
             exit_code, exit_code == 0 ? " (no changes)" : " (changes detected)");
    if (exit_code == 0) return aegis_result_ok(msg);
    return aegis_result_warn(msg);
}
