#define _POSIX_C_SOURCE 200809L
#include <aegis/modules/dns.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define RESOLVED_CONF_PATH "/etc/systemd/resolved.conf"

aegis_result_t aegis_dns_apply(const void *config, aegis_executor_t *exec) {
    const aegis_dns_config_t *cfg = config;
    if (!cfg || !cfg->enabled)
        return aegis_result_skip("dns: disabled");

    aegis_result_t res = aegis_result_ok("dns: applied");

    const char *dnssec_val = cfg->dnssec ? "yes" : "no";
    const char *dot_val    = cfg->dot    ? "yes" : "no";

    char conf[512];
    snprintf(conf, sizeof(conf),
             "# Generated by aegis\n"
             "[Resolve]\n"
             "DNSSEC=%s\n"
             "DNSOverTLS=%s\n",
             dnssec_val, dot_val);

    if (exec->write_file(RESOLVED_CONF_PATH, conf, true, exec->ctx) != 0) {
        aegis_result_free(&res);
        return aegis_result_fail("dns: failed to write " RESOLVED_CONF_PATH);
    }
    aegis_result_add_action(&res, "Wrote " RESOLVED_CONF_PATH);

    /* Restart systemd-resolved */
    const char *restart[] = {"systemctl", "restart", "systemd-resolved", NULL};
    aegis_exec_result_t r = exec->execute_sudo(restart, exec->ctx);
    aegis_exec_result_free(&r);
    aegis_result_add_action(&res, "Restarted systemd-resolved");

    char msg[128];
    snprintf(msg, sizeof(msg), "dns: DNSSEC=%s DNSOverTLS=%s", dnssec_val, dot_val);
    free(res.message);
    res.message = strdup(msg);
    return res;
}

aegis_result_t aegis_dns_status(aegis_executor_t *exec) {
    const char *argv[] = {"systemctl", "is-active", "systemd-resolved", NULL};
    aegis_exec_result_t r = exec->execute(argv, exec->ctx);
    bool active = (r.exit_code == 0);
    aegis_exec_result_free(&r);

    bool conf_exists = exec->file_exists(RESOLVED_CONF_PATH, exec->ctx);

    char msg[128];
    snprintf(msg, sizeof(msg), "dns: service=%s config=%s",
             active ? "active" : "inactive", conf_exists ? "present" : "missing");
    if (active && conf_exists) return aegis_result_ok(msg);
    if (active || conf_exists) return aegis_result_warn(msg);
    return aegis_result_fail(msg);
}

aegis_result_t aegis_dns_verify(aegis_executor_t *exec) {
    return aegis_dns_status(exec);
}
