#define _POSIX_C_SOURCE 200809L
#include <aegis/modules/dropbear.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MKINITCPIO_CONF "/etc/mkinitcpio.conf"

/* Add dropbear to the HOOKS line in mkinitcpio.conf */
static char *inject_dropbear_hook(const char *original) {
    if (!original) return NULL;

    /* If already present, return a copy unchanged */
    if (strstr(original, "dropbear")) return strdup(original);

    /* Find the HOOKS line and add dropbear before 'filesystems' or at the end of the array */
    char *result = malloc(strlen(original) + 32);
    if (!result) return NULL;

    const char *pos = strstr(original, "filesystems");
    if (pos) {
        size_t before = (size_t)(pos - original);
        strncpy(result, original, before);
        result[before] = '\0';
        strcat(result, "dropbear ");
        strcat(result, pos);
    } else {
        /* fallback: append before closing paren if present */
        const char *rparen = strrchr(original, ')');
        if (rparen) {
            size_t before = (size_t)(rparen - original);
            strncpy(result, original, before);
            result[before] = '\0';
            strcat(result, "dropbear)");
            strcat(result, rparen + 1);
        } else {
            strcpy(result, original);
            free(result);
            return strdup(original);
        }
    }
    return result;
}

aegis_result_t aegis_dropbear_apply(const void *config, aegis_executor_t *exec) {
    const aegis_dropbear_config_t *cfg = config;
    if (!cfg || !cfg->enabled)
        return aegis_result_skip("dropbear: disabled");

    aegis_result_t res = aegis_result_ok("dropbear: applied");

    /* Install dropbear */
    const char *install[] = {"pacman", "-S", "--noconfirm", "--needed", "dropbear", NULL};
    aegis_exec_result_t r = exec->execute_sudo(install, exec->ctx);
    if (r.exit_code != 0) {
        aegis_result_free(&res);
        aegis_exec_result_free(&r);
        return aegis_result_fail("dropbear: pacman -S failed");
    }
    aegis_exec_result_free(&r);
    aegis_result_add_action(&res, "Ensured dropbear package installed");

    /* Read mkinitcpio.conf */
    char *existing = exec->read_file(MKINITCPIO_CONF, exec->ctx);
    const char *base = existing ? existing :
        "# Generated by aegis\n"
        "HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)\n";

    char *updated = inject_dropbear_hook(base);
    free(existing);

    if (updated) {
        if (exec->write_file(MKINITCPIO_CONF, updated, true, exec->ctx) != 0) {
            free(updated);
            aegis_result_free(&res);
            return aegis_result_fail("dropbear: failed to write " MKINITCPIO_CONF);
        }
        free(updated);
        aegis_result_add_action(&res, "Added dropbear hook to " MKINITCPIO_CONF);
    }

    /* Regenerate initramfs */
    const char *mkinitcpio[] = {"mkinitcpio", "-P", NULL};
    r = exec->execute_sudo(mkinitcpio, exec->ctx);
    if (r.exit_code != 0) {
        aegis_result_free(&res);
        aegis_exec_result_free(&r);
        return aegis_result_fail("dropbear: mkinitcpio -P failed");
    }
    aegis_exec_result_free(&r);
    aegis_result_add_action(&res, "Regenerated initramfs with mkinitcpio -P");

    return res;
}

aegis_result_t aegis_dropbear_status(aegis_executor_t *exec) {
    bool conf_exists = exec->file_exists(MKINITCPIO_CONF, exec->ctx);
    bool in_hooks = false;

    if (conf_exists) {
        char *content = exec->read_file(MKINITCPIO_CONF, exec->ctx);
        in_hooks = content && strstr(content, "dropbear") != NULL;
        free(content);
    }

    char msg[128];
    snprintf(msg, sizeof(msg), "dropbear: mkinitcpio.conf=%s hook=%s",
             conf_exists ? "present" : "missing", in_hooks ? "present" : "missing");
    if (in_hooks) return aegis_result_ok(msg);
    return aegis_result_fail(msg);
}

aegis_result_t aegis_dropbear_verify(aegis_executor_t *exec) {
    /* Per-item compliance: binary present, hook in mkinitcpio.conf */
    aegis_result_t res = aegis_result_ok("dropbear: all checks passed");
    int total = 0, passed = 0;

    /* Check 1: dropbear binary exists */
    total++;
    bool installed = exec->file_exists("/usr/bin/dropbear", exec->ctx);
    aegis_result_add_action(&res, installed
        ? "PASS: /usr/bin/dropbear present"
        : "FAIL: /usr/bin/dropbear not found — dropbear not installed");
    if (installed) passed++;

    /* Check 2: mkinitcpio.conf contains dropbear hook */
    total++;
    char *content = exec->read_file(MKINITCPIO_CONF, exec->ctx);
    bool in_hooks = (content && strstr(content, "dropbear") != NULL);
    free(content);
    aegis_result_add_action(&res, in_hooks
        ? "PASS: dropbear hook present in " MKINITCPIO_CONF
        : "FAIL: dropbear hook missing from " MKINITCPIO_CONF);
    if (in_hooks) passed++;

    char msg[128];
    snprintf(msg, sizeof(msg), "dropbear: %d/%d checks passed", passed, total);
    free(res.message);
    res.message = strdup(msg);

    if (passed == total) {
        res.status = AEGIS_OK;
    } else if (passed > 0) {
        res.status = AEGIS_WARN;
    } else {
        res.status = AEGIS_FAIL;
    }
    return res;
}
