#define _POSIX_C_SOURCE 200809L
#include <aegis/modules/fail2ban.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define FAIL2BAN_JAIL_CONF "/etc/fail2ban/jail.d/aegis.conf"

static const char *JAIL_MINIMAL =
    "# Generated by aegis (minimal profile)\n"
    "[sshd]\n"
    "enabled = true\n"
    "maxretry = 5\n"
    "bantime = 3600\n";

static const char *JAIL_STANDARD =
    "# Generated by aegis (standard profile)\n"
    "[sshd]\n"
    "enabled = true\n"
    "maxretry = 5\n"
    "bantime = 3600\n"
    "\n"
    "[recidive]\n"
    "enabled = true\n"
    "bantime = 86400\n"
    "findtime = 86400\n"
    "maxretry = 5\n";

static const char *JAIL_STRICT =
    "# Generated by aegis (strict profile)\n"
    "[sshd]\n"
    "enabled = true\n"
    "maxretry = 3\n"
    "bantime = 86400\n"
    "\n"
    "[recidive]\n"
    "enabled = true\n"
    "bantime = 604800\n"
    "findtime = 86400\n"
    "maxretry = 3\n";

aegis_result_t aegis_fail2ban_apply(const void *config, aegis_executor_t *exec) {
    const aegis_fail2ban_config_t *cfg = config;
    if (!cfg || !cfg->enabled)
        return aegis_result_skip("fail2ban: disabled");

    aegis_result_t res = aegis_result_ok("fail2ban: applied");

    /* Install fail2ban */
    const char *install[] = {"pacman", "-S", "--noconfirm", "--needed", "fail2ban", NULL};
    aegis_exec_result_t r = exec->execute_sudo(install, exec->ctx);
    if (r.exit_code != 0) {
        aegis_result_free(&res);
        aegis_exec_result_free(&r);
        return aegis_result_fail("fail2ban: pacman -S failed");
    }
    aegis_exec_result_free(&r);
    aegis_result_add_action(&res, "Ensured fail2ban package installed");

    /* Select jail config based on profile */
    const char *profile = (cfg->profile && cfg->profile[0]) ? cfg->profile : "standard";
    const char *jail_content;
    if (strcmp(profile, "minimal") == 0) {
        jail_content = JAIL_MINIMAL;
    } else if (strcmp(profile, "strict") == 0) {
        jail_content = JAIL_STRICT;
    } else {
        jail_content = JAIL_STANDARD;
    }

    if (exec->write_file(FAIL2BAN_JAIL_CONF, jail_content, true, exec->ctx) != 0) {
        aegis_result_free(&res);
        return aegis_result_fail("fail2ban: failed to write " FAIL2BAN_JAIL_CONF);
    }

    char action_msg[128];
    snprintf(action_msg, sizeof(action_msg),
             "Wrote %s with %s profile", FAIL2BAN_JAIL_CONF, profile);
    aegis_result_add_action(&res, action_msg);

    /* Enable fail2ban service */
    const char *enable[] = {"systemctl", "enable", "--now", "fail2ban", NULL};
    r = exec->execute_sudo(enable, exec->ctx);
    if (r.exit_code != 0) {
        aegis_result_free(&res);
        aegis_exec_result_free(&r);
        return aegis_result_fail("fail2ban: systemctl enable fail2ban failed");
    }
    aegis_exec_result_free(&r);
    aegis_result_add_action(&res, "Enabled fail2ban service");

    char msg[128];
    snprintf(msg, sizeof(msg), "fail2ban: applied with %s profile", profile);
    free(res.message);
    res.message = strdup(msg);
    return res;
}

static aegis_result_t check_fail2ban(aegis_executor_t *exec) {
    /* Check service is active */
    const char *svc_argv[] = {"systemctl", "is-active", "fail2ban", NULL};
    aegis_exec_result_t r = exec->execute(svc_argv, exec->ctx);
    bool active = (r.exit_code == 0);
    aegis_exec_result_free(&r);

    /* List jails */
    const char *jails_argv[] = {"fail2ban-client", "status", NULL};
    r = exec->execute(jails_argv, exec->ctx);
    char *jails_out = r.stdout_buf ? strdup(r.stdout_buf) : strdup("");
    aegis_exec_result_free(&r);

    char msg[256];
    snprintf(msg, sizeof(msg), "fail2ban: service=%s jails=%s",
             active ? "active" : "inactive",
             jails_out[0] ? jails_out : "none");
    free(jails_out);

    if (active) return aegis_result_ok(msg);
    return aegis_result_fail(msg);
}

aegis_result_t aegis_fail2ban_status(aegis_executor_t *exec) {
    return check_fail2ban(exec);
}

aegis_result_t aegis_fail2ban_verify(aegis_executor_t *exec) {
    /* Per-item compliance: service active, aegis config file present, jails loaded */
    aegis_result_t res = aegis_result_ok("fail2ban: all checks passed");
    int total = 0, passed = 0;

    /* Check 1: service active */
    total++;
    const char *svc_argv[] = {"systemctl", "is-active", "fail2ban", NULL};
    aegis_exec_result_t r = exec->execute(svc_argv, exec->ctx);
    bool active = (r.exit_code == 0);
    aegis_exec_result_free(&r);
    aegis_result_add_action(&res, active
        ? "PASS: fail2ban service is active"
        : "FAIL: fail2ban service is not active");
    if (active) passed++;

    /* Check 2: aegis jail config file exists */
    total++;
    bool conf_exists = exec->file_exists(FAIL2BAN_JAIL_CONF, exec->ctx);
    aegis_result_add_action(&res, conf_exists
        ? "PASS: " FAIL2BAN_JAIL_CONF " present"
        : "FAIL: " FAIL2BAN_JAIL_CONF " missing");
    if (conf_exists) passed++;

    /* Check 3: sshd jail loaded */
    total++;
    const char *status_argv[] = {"fail2ban-client", "status", "sshd", NULL};
    r = exec->execute(status_argv, exec->ctx);
    bool sshd_loaded = (r.exit_code == 0);
    aegis_exec_result_free(&r);
    aegis_result_add_action(&res, sshd_loaded
        ? "PASS: sshd jail is active in fail2ban"
        : "FAIL: sshd jail is not active in fail2ban");
    if (sshd_loaded) passed++;

    char msg[128];
    snprintf(msg, sizeof(msg), "fail2ban: %d/%d checks passed", passed, total);
    free(res.message);
    res.message = strdup(msg);

    if (passed == total) {
        res.status = AEGIS_OK;
    } else if (passed > total / 2) {
        res.status = AEGIS_WARN;
    } else {
        res.status = AEGIS_FAIL;
    }
    return res;
}
