#define _POSIX_C_SOURCE 200809L
#include <aegis/modules/mounts.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

static const char TMP_MOUNT_UNIT[] =
    "# Generated by aegis\n"
    "[Unit]\n"
    "Description=Temporary Directory (/tmp)\n"
    "ConditionPathIsSymbolicLink=!/tmp\n"
    "DefaultDependencies=no\n"
    "Conflicts=umount.target\n"
    "Before=local-fs.target umount.target\n\n"
    "[Mount]\n"
    "What=tmpfs\n"
    "Where=/tmp\n"
    "Type=tmpfs\n"
    "Options=mode=1777,strictatime,noexec,nodev,nosuid,size=50%%\n\n"
    "[Install]\n"
    "WantedBy=local-fs.target\n";

static const char DEV_SHM_FSTAB[] = "tmpfs /dev/shm tmpfs defaults,noexec,nodev,nosuid 0 0\n";
static const char PROC_FSTAB[] = "proc /proc proc defaults,hidepid=2 0 0\n";

aegis_result_t aegis_mounts_apply(const void *config, aegis_executor_t *exec) {
    const aegis_mounts_config_t *cfg = config;
    if (!cfg || !cfg->enabled)
        return aegis_result_skip("mounts: disabled");

    aegis_result_t res = aegis_result_ok("mounts: hardened");

    if (cfg->harden_tmp) {
        if (exec->write_file("/etc/systemd/system/tmp.mount", TMP_MOUNT_UNIT, true, exec->ctx) != 0) {
            aegis_result_free(&res);
            return aegis_result_fail("mounts: failed to write /etc/systemd/system/tmp.mount");
        }
        const char *enable[] = {"systemctl", "enable", "--now", "tmp.mount", NULL};
        aegis_exec_result_t r = exec->execute_sudo(enable, exec->ctx);
        if (r.exit_code != 0) {
            aegis_result_free(&res);
            aegis_exec_result_free(&r);
            return aegis_result_fail("mounts: systemctl enable tmp.mount failed");
        }
        aegis_exec_result_free(&r);
        aegis_result_add_action(&res, "Hardened /tmp (noexec,nodev,nosuid via tmp.mount)");
    }

    if (cfg->harden_dev_shm) {
        /* Append to fstab if not already present */
        char *fstab = exec->read_file("/etc/fstab", exec->ctx);
        if (!fstab || !strstr(fstab, "/dev/shm")) {
            size_t fstab_len = fstab ? strlen(fstab) : 0;
            size_t entry_len = strlen(DEV_SHM_FSTAB);
            char *new_fstab = malloc(fstab_len + entry_len + 1);
            if (!new_fstab) {
                free(fstab);
                aegis_result_free(&res);
                return aegis_result_fail("mounts: malloc failed");
            }
            if (fstab) memcpy(new_fstab, fstab, fstab_len);
            memcpy(new_fstab + fstab_len, DEV_SHM_FSTAB, entry_len + 1);
            if (exec->write_file("/etc/fstab", new_fstab, true, exec->ctx) != 0) {
                free(new_fstab);
                free(fstab);
                aegis_result_free(&res);
                return aegis_result_fail("mounts: failed to write /etc/fstab");
            }
            free(new_fstab);
        }
        free(fstab);
        const char *remount[] = {"mount", "-o", "remount", "/dev/shm", NULL};
        aegis_exec_result_t r = exec->execute_sudo(remount, exec->ctx);
        aegis_exec_result_free(&r);
        aegis_result_add_action(&res, "Hardened /dev/shm (noexec,nodev,nosuid)");
    }

    if (cfg->harden_proc) {
        char *fstab = exec->read_file("/etc/fstab", exec->ctx);
        if (!fstab || !strstr(fstab, "hidepid")) {
            size_t fstab_len = fstab ? strlen(fstab) : 0;
            size_t entry_len = strlen(PROC_FSTAB);
            char *new_fstab = malloc(fstab_len + entry_len + 1);
            if (!new_fstab) {
                free(fstab);
                aegis_result_free(&res);
                return aegis_result_fail("mounts: malloc failed");
            }
            if (fstab) memcpy(new_fstab, fstab, fstab_len);
            memcpy(new_fstab + fstab_len, PROC_FSTAB, entry_len + 1);
            if (exec->write_file("/etc/fstab", new_fstab, true, exec->ctx) != 0) {
                free(new_fstab);
                free(fstab);
                aegis_result_free(&res);
                return aegis_result_fail("mounts: failed to write /etc/fstab");
            }
            free(new_fstab);
        }
        free(fstab);
        const char *remount[] = {"mount", "-o", "remount", "/proc", NULL};
        aegis_exec_result_t r = exec->execute_sudo(remount, exec->ctx);
        aegis_exec_result_free(&r);
        aegis_result_add_action(&res, "Hardened /proc (hidepid=2)");
    }

    return res;
}

aegis_result_t aegis_mounts_status(aegis_executor_t *exec) {
    const char *argv[] = {"mount", NULL};
    aegis_exec_result_t r = exec->execute(argv, exec->ctx);
    /* Parse mount output for hardening flags */
    int hardened = 0;
    if (r.stdout_buf) {
        if (strstr(r.stdout_buf, "/tmp") && strstr(r.stdout_buf, "noexec")) hardened++;
        if (strstr(r.stdout_buf, "/dev/shm") && strstr(r.stdout_buf, "noexec")) hardened++;
        if (strstr(r.stdout_buf, "/proc") && strstr(r.stdout_buf, "hidepid")) hardened++;
    }
    aegis_exec_result_free(&r);

    char msg[128];
    snprintf(msg, sizeof(msg), "mounts: %d/3 hardened", hardened);
    if (hardened == 3) return aegis_result_ok(msg);
    if (hardened > 0)  return aegis_result_warn(msg);
    return aegis_result_fail(msg);
}

aegis_result_t aegis_mounts_verify(aegis_executor_t *exec) {
    /* Per-mount-point compliance check */
    aegis_result_t res = aegis_result_ok("mounts: all hardening checks passed");
    int total = 0, passed = 0;

    const char *argv[] = {"mount", NULL};
    aegis_exec_result_t r = exec->execute(argv, exec->ctx);
    const char *out = r.stdout_buf ? r.stdout_buf : "";

    /* Check /tmp: must have noexec, nodev, nosuid */
    total++;
    bool tmp_ok = (strstr(out, "/tmp") && strstr(out, "noexec") &&
                   strstr(out, "nodev") && strstr(out, "nosuid"));
    aegis_result_add_action(&res, tmp_ok
        ? "PASS: /tmp mounted with noexec,nodev,nosuid"
        : "FAIL: /tmp missing one or more of noexec,nodev,nosuid");
    if (tmp_ok) passed++;

    /* Check /dev/shm: must have noexec, nodev, nosuid */
    total++;
    bool shm_ok = (strstr(out, "/dev/shm") && strstr(out, "noexec") &&
                   strstr(out, "nodev") && strstr(out, "nosuid"));
    aegis_result_add_action(&res, shm_ok
        ? "PASS: /dev/shm mounted with noexec,nodev,nosuid"
        : "FAIL: /dev/shm missing one or more of noexec,nodev,nosuid");
    if (shm_ok) passed++;

    /* Check /proc: must have hidepid */
    total++;
    bool proc_ok = (strstr(out, "/proc") && strstr(out, "hidepid"));
    aegis_result_add_action(&res, proc_ok
        ? "PASS: /proc mounted with hidepid"
        : "FAIL: /proc not mounted with hidepid");
    if (proc_ok) passed++;

    aegis_exec_result_free(&r);

    char msg[128];
    snprintf(msg, sizeof(msg), "mounts: %d/%d hardened", passed, total);
    free(res.message);
    res.message = strdup(msg);

    if (passed == total) {
        res.status = AEGIS_OK;
    } else if (passed > 0) {
        res.status = AEGIS_WARN;
    } else {
        res.status = AEGIS_FAIL;
    }
    return res;
}
