#define _POSIX_C_SOURCE 200809L
#include <aegis/modules/mounts.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

static const char TMP_MOUNT_UNIT[] =
    "# Generated by aegis\n"
    "[Unit]\n"
    "Description=Temporary Directory (/tmp)\n"
    "ConditionPathIsSymbolicLink=!/tmp\n"
    "DefaultDependencies=no\n"
    "Conflicts=umount.target\n"
    "Before=local-fs.target umount.target\n\n"
    "[Mount]\n"
    "What=tmpfs\n"
    "Where=/tmp\n"
    "Type=tmpfs\n"
    "Options=mode=1777,strictatime,noexec,nodev,nosuid,size=50%%\n\n"
    "[Install]\n"
    "WantedBy=local-fs.target\n";

static const char DEV_SHM_FSTAB[] = "tmpfs /dev/shm tmpfs defaults,noexec,nodev,nosuid 0 0\n";
static const char PROC_FSTAB[] = "proc /proc proc defaults,hidepid=2 0 0\n";

aegis_result_t aegis_mounts_apply(const void *config, aegis_executor_t *exec) {
    const aegis_mounts_config_t *cfg = config;
    if (!cfg || !cfg->enabled)
        return aegis_result_skip("mounts: disabled");

    aegis_result_t res = aegis_result_ok("mounts: hardened");

    if (cfg->harden_tmp) {
        exec->write_file("/etc/systemd/system/tmp.mount", TMP_MOUNT_UNIT, true, exec->ctx);
        const char *enable[] = {"systemctl", "enable", "--now", "tmp.mount", NULL};
        aegis_exec_result_t r = exec->execute_sudo(enable, exec->ctx);
        aegis_exec_result_free(&r);
        aegis_result_add_action(&res, "Hardened /tmp (noexec,nodev,nosuid via tmp.mount)");
    }

    if (cfg->harden_dev_shm) {
        /* Append to fstab if not already present */
        char *fstab = exec->read_file("/etc/fstab", exec->ctx);
        if (!fstab || !strstr(fstab, "/dev/shm")) {
            char new_fstab[8192] = {0};
            if (fstab) strncpy(new_fstab, fstab, sizeof(new_fstab) - 256);
            strcat(new_fstab, DEV_SHM_FSTAB);
            exec->write_file("/etc/fstab", new_fstab, true, exec->ctx);
        }
        free(fstab);
        const char *remount[] = {"mount", "-o", "remount", "/dev/shm", NULL};
        aegis_exec_result_t r = exec->execute_sudo(remount, exec->ctx);
        aegis_exec_result_free(&r);
        aegis_result_add_action(&res, "Hardened /dev/shm (noexec,nodev,nosuid)");
    }

    if (cfg->harden_proc) {
        char *fstab = exec->read_file("/etc/fstab", exec->ctx);
        if (!fstab || !strstr(fstab, "hidepid")) {
            char new_fstab[8192] = {0};
            if (fstab) strncpy(new_fstab, fstab, sizeof(new_fstab) - 256);
            strcat(new_fstab, PROC_FSTAB);
            exec->write_file("/etc/fstab", new_fstab, true, exec->ctx);
        }
        free(fstab);
        const char *remount[] = {"mount", "-o", "remount", "/proc", NULL};
        aegis_exec_result_t r = exec->execute_sudo(remount, exec->ctx);
        aegis_exec_result_free(&r);
        aegis_result_add_action(&res, "Hardened /proc (hidepid=2)");
    }

    return res;
}

aegis_result_t aegis_mounts_status(aegis_executor_t *exec) {
    const char *argv[] = {"mount", NULL};
    aegis_exec_result_t r = exec->execute(argv, exec->ctx);
    /* Parse mount output for hardening flags */
    int hardened = 0;
    if (r.stdout_buf) {
        if (strstr(r.stdout_buf, "/tmp") && strstr(r.stdout_buf, "noexec")) hardened++;
        if (strstr(r.stdout_buf, "/dev/shm") && strstr(r.stdout_buf, "noexec")) hardened++;
        if (strstr(r.stdout_buf, "/proc") && strstr(r.stdout_buf, "hidepid")) hardened++;
    }
    aegis_exec_result_free(&r);

    char msg[128];
    snprintf(msg, sizeof(msg), "mounts: %d/3 hardened", hardened);
    if (hardened == 3) return aegis_result_ok(msg);
    if (hardened > 0)  return aegis_result_warn(msg);
    return aegis_result_fail(msg);
}

aegis_result_t aegis_mounts_verify(aegis_executor_t *exec) {
    return aegis_mounts_status(exec);
}
