#define _POSIX_C_SOURCE 200809L
#include <aegis/modules/snapper.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static const char *pacman_hook =
    "# Generated by aegis\n"
    "[Trigger]\n"
    "Operation = Upgrade\n"
    "Operation = Install\n"
    "Operation = Remove\n"
    "Type = Package\n"
    "Target = *\n"
    "\n"
    "[Action]\n"
    "Description = Creating pre/post btrfs snapshots...\n"
    "When = PreTransaction\n"
    "Exec = /usr/bin/snap-pac-pre\n"
    "NeedsTargets\n"
    "\n"
    "[Trigger]\n"
    "Operation = Upgrade\n"
    "Operation = Install\n"
    "Operation = Remove\n"
    "Type = Package\n"
    "Target = *\n"
    "\n"
    "[Action]\n"
    "Description = Creating pre/post btrfs snapshots...\n"
    "When = PostTransaction\n"
    "Exec = /usr/bin/snap-pac-post\n"
    "NeedsTargets\n";

/* Derive a config name from a subvolume path: "/" -> "root", "/home" -> "home" */
static const char *config_name_for(const char *path) {
    if (strcmp(path, "/") == 0) return "root";
    const char *slash = strrchr(path, '/');
    return (slash && slash[1]) ? slash + 1 : path;
}

aegis_result_t aegis_snapper_apply(const void *config, aegis_executor_t *exec) {
    const aegis_snapper_config_t *cfg = config;
    if (!cfg || !cfg->enabled)
        return aegis_result_skip("snapper: disabled");

    aegis_result_t res = aegis_result_ok("snapper: applied");

    /* Install snapper + snap-pac */
    const char *install[] = {"pacman", "-S", "--noconfirm", "--needed", "snapper", "snap-pac", NULL};
    aegis_exec_result_t r = exec->execute_sudo(install, exec->ctx);
    if (r.exit_code != 0) {
        aegis_result_free(&res);
        aegis_exec_result_free(&r);
        return aegis_result_fail("snapper: pacman -S failed");
    }
    aegis_exec_result_free(&r);
    aegis_result_add_action(&res, "Ensured snapper and snap-pac packages installed");

    /* Create config for each subvolume */
    for (int i = 0; i < cfg->subvolume_count; i++) {
        const char *path = cfg->subvolumes[i];
        const char *name = config_name_for(path);
        const char *create[] = {"snapper", "-c", name, "create-config", path, NULL};
        r = exec->execute_sudo(create, exec->ctx);
        aegis_exec_result_free(&r);
        char action[256];
        snprintf(action, sizeof(action), "Created snapper config '%s' for %s", name, path);
        aegis_result_add_action(&res, action);
    }

    /* Install pacman hook */
    if (exec->write_file("/etc/pacman.d/hooks/snap-pac.hook", pacman_hook, true, exec->ctx) != 0) {
        aegis_result_free(&res);
        return aegis_result_fail("snapper: failed to write /etc/pacman.d/hooks/snap-pac.hook");
    }
    aegis_result_add_action(&res, "Installed snap-pac pacman hook");

    char msg[128];
    snprintf(msg, sizeof(msg), "snapper: configured %d subvolume(s)", cfg->subvolume_count);
    free(res.message);
    res.message = strdup(msg);
    return res;
}

aegis_result_t aegis_snapper_status(aegis_executor_t *exec) {
    bool hook_exists = exec->file_exists("/etc/pacman.d/hooks/snap-pac.hook", exec->ctx);

    char msg[128];
    snprintf(msg, sizeof(msg), "snapper: hook=%s", hook_exists ? "present" : "missing");
    if (hook_exists) return aegis_result_ok(msg);
    return aegis_result_fail(msg);
}

aegis_result_t aegis_snapper_verify(aegis_executor_t *exec) {
    /* Per-item compliance: hook present, snapper binary available, configs listed */
    aegis_result_t res = aegis_result_ok("snapper: all checks passed");
    int total = 0, passed = 0;

    /* Check 1: snap-pac hook present */
    total++;
    bool hook_exists = exec->file_exists("/etc/pacman.d/hooks/snap-pac.hook", exec->ctx);
    aegis_result_add_action(&res, hook_exists
        ? "PASS: /etc/pacman.d/hooks/snap-pac.hook present"
        : "FAIL: /etc/pacman.d/hooks/snap-pac.hook missing");
    if (hook_exists) passed++;

    /* Check 2: snapper binary present */
    total++;
    bool snapper_installed = exec->file_exists("/usr/bin/snapper", exec->ctx);
    aegis_result_add_action(&res, snapper_installed
        ? "PASS: /usr/bin/snapper present"
        : "FAIL: /usr/bin/snapper not found — snapper not installed");
    if (snapper_installed) passed++;

    /* Check 3: snapper can list configs */
    total++;
    const char *list_argv[] = {"snapper", "list-configs", NULL};
    aegis_exec_result_t r = exec->execute_sudo(list_argv, exec->ctx);
    bool configs_ok = (r.exit_code == 0);
    aegis_exec_result_free(&r);
    aegis_result_add_action(&res, configs_ok
        ? "PASS: snapper list-configs succeeded"
        : "FAIL: snapper list-configs failed — no configs or not on btrfs");
    if (configs_ok) passed++;

    char msg[128];
    snprintf(msg, sizeof(msg), "snapper: %d/%d checks passed", passed, total);
    free(res.message);
    res.message = strdup(msg);

    if (passed == total) {
        res.status = AEGIS_OK;
    } else if (passed > 0) {
        res.status = AEGIS_WARN;
    } else {
        res.status = AEGIS_FAIL;
    }
    return res;
}
