#define _POSIX_C_SOURCE 200809L
#include <aegis/modules/sysctl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct { const char *key; const char *value; } sysctl_param_t;

static const sysctl_param_t profile_minimal[] = {
    {"kernel.kptr_restrict", "1"},
    {"kernel.dmesg_restrict", "1"},
    {"net.core.bpf_jit_harden", "2"},
    {NULL, NULL}
};

static const sysctl_param_t profile_standard[] = {
    {"kernel.kptr_restrict", "2"},
    {"kernel.dmesg_restrict", "1"},
    {"kernel.perf_event_paranoid", "3"},
    {"kernel.kexec_load_disabled", "1"},
    {"kernel.unprivileged_bpf_disabled", "1"},
    {"net.core.bpf_jit_harden", "2"},
    {"net.ipv4.conf.all.rp_filter", "1"},
    {"net.ipv4.conf.default.rp_filter", "1"},
    {"net.ipv4.conf.all.accept_redirects", "0"},
    {"net.ipv4.conf.default.accept_redirects", "0"},
    {"net.ipv4.conf.all.send_redirects", "0"},
    {"net.ipv6.conf.all.accept_redirects", "0"},
    {"net.ipv6.conf.default.accept_redirects", "0"},
    {NULL, NULL}
};

static const sysctl_param_t profile_paranoid[] = {
    {"kernel.kptr_restrict", "2"},
    {"kernel.dmesg_restrict", "1"},
    {"kernel.perf_event_paranoid", "3"},
    {"kernel.kexec_load_disabled", "1"},
    {"kernel.unprivileged_bpf_disabled", "1"},
    {"kernel.yama.ptrace_scope", "3"},
    {"net.core.bpf_jit_harden", "2"},
    {"net.ipv4.conf.all.rp_filter", "1"},
    {"net.ipv4.conf.default.rp_filter", "1"},
    {"net.ipv4.conf.all.accept_redirects", "0"},
    {"net.ipv4.conf.default.accept_redirects", "0"},
    {"net.ipv4.conf.all.send_redirects", "0"},
    {"net.ipv4.conf.all.accept_source_route", "0"},
    {"net.ipv4.conf.default.accept_source_route", "0"},
    {"net.ipv4.tcp_syncookies", "1"},
    {"net.ipv6.conf.all.accept_redirects", "0"},
    {"net.ipv6.conf.default.accept_redirects", "0"},
    {"net.ipv6.conf.all.accept_source_route", "0"},
    {"net.ipv6.conf.default.accept_source_route", "0"},
    {"vm.mmap_rnd_bits", "32"},
    {"vm.mmap_rnd_compat_bits", "16"},
    {NULL, NULL}
};

static const sysctl_param_t *get_profile(const char *name) {
    if (name && strcmp(name, "minimal") == 0) return profile_minimal;
    if (name && strcmp(name, "paranoid") == 0) return profile_paranoid;
    return profile_standard; /* default */
}

aegis_result_t aegis_sysctl_apply(const void *config, aegis_executor_t *exec) {
    const aegis_sysctl_config_t *cfg = config;
    if (!cfg || !cfg->enabled)
        return aegis_result_skip("sysctl: disabled");

    const sysctl_param_t *params = get_profile(cfg->profile);
    aegis_result_t res = aegis_result_ok("sysctl: applied");

    /* Build persistent config file content */
    static const char header[] = "# Generated by aegis \xe2\x80\x94 do not edit\n";
    size_t cap = 4096;
    size_t pos = 0;
    char *file_buf = malloc(cap);
    if (!file_buf) {
        aegis_result_free(&res);
        return aegis_result_fail("sysctl: malloc failed");
    }
    pos += (size_t)snprintf(file_buf + pos, cap - pos, "%s", header);

    for (const sysctl_param_t *p = params; p->key; p++) {
        /* Ensure we have space for the next line (key + " = " + value + "\n" + NUL) */
        size_t needed = strlen(p->key) + strlen(p->value) + 5;
        if (pos + needed >= cap) {
            cap *= 2;
            char *tmp = realloc(file_buf, cap);
            if (!tmp) { free(file_buf); aegis_result_free(&res); return aegis_result_fail("sysctl: realloc failed"); }
            file_buf = tmp;
        }
        int n = snprintf(file_buf + pos, cap - pos, "%s = %s\n", p->key, p->value);
        pos += (size_t)n;

        char action[256];
        snprintf(action, sizeof(action), "Set %s = %s", p->key, p->value);
        aegis_result_add_action(&res, action);
    }

    /* Write persistent config */
    if (exec->write_file("/etc/sysctl.d/99-aegis.conf", file_buf, true, exec->ctx) != 0) {
        free(file_buf);
        aegis_result_free(&res);
        return aegis_result_fail("sysctl: failed to write /etc/sysctl.d/99-aegis.conf");
    }
    free(file_buf);
    aegis_result_add_action(&res, "Wrote /etc/sysctl.d/99-aegis.conf");

    /* Reload sysctl */
    const char *reload[] = {"sysctl", "--system", NULL};
    aegis_exec_result_t r = exec->execute_sudo(reload, exec->ctx);
    if (r.exit_code != 0) {
        /* Config was written but not loaded — downgrade to WARN */
        res.status = AEGIS_WARN;
        aegis_result_add_action(&res, "WARNING: sysctl --system failed; config written but not loaded");
    } else {
        aegis_result_add_action(&res, "Reloaded sysctl");
    }
    aegis_exec_result_free(&r);

    char msg[128];
    snprintf(msg, sizeof(msg), "sysctl: applied %s profile", cfg->profile ? cfg->profile : "standard");
    free(res.message);
    res.message = strdup(msg);
    return res;
}

aegis_result_t aegis_sysctl_status(aegis_executor_t *exec) {
    const sysctl_param_t *params = profile_standard;
    int total = 0, matched = 0;

    for (const sysctl_param_t *p = params; p->key; p++) {
        total++;
        const char *argv[] = {"sysctl", p->key, NULL};
        aegis_exec_result_t r = exec->execute(argv, exec->ctx);

        if (r.exit_code == 0 && r.stdout_buf) {
            /* Parse "key = value\n" */
            char *eq = strstr(r.stdout_buf, "= ");
            if (eq) {
                eq += 2;
                char *nl = strchr(eq, '\n');
                if (nl) *nl = '\0';
                if (strcmp(eq, p->value) == 0) matched++;
            }
        }
        aegis_exec_result_free(&r);
    }

    char msg[128];
    snprintf(msg, sizeof(msg), "sysctl: %d/%d parameters match standard profile", matched, total);
    if (matched == total) return aegis_result_ok(msg);
    if (matched > 0)      return aegis_result_warn(msg);
    return aegis_result_fail(msg);
}

aegis_result_t aegis_sysctl_verify(aegis_executor_t *exec) {
    /* Per-parameter compliance check — distinct from status() */
    const sysctl_param_t *params = profile_standard;
    int total = 0, passed = 0;
    aegis_result_t res = aegis_result_ok("sysctl: all parameters compliant");

    for (const sysctl_param_t *p = params; p->key; p++) {
        total++;
        const char *argv[] = {"sysctl", p->key, NULL};
        aegis_exec_result_t r = exec->execute(argv, exec->ctx);

        bool ok = false;
        if (r.exit_code == 0 && r.stdout_buf) {
            char *eq = strstr(r.stdout_buf, "= ");
            if (eq) {
                eq += 2;
                char *nl = strchr(eq, '\n');
                if (nl) *nl = '\0';
                ok = (strcmp(eq, p->value) == 0);
            }
        }
        aegis_exec_result_free(&r);

        char action[256];
        if (ok) {
            snprintf(action, sizeof(action), "PASS: %s = %s", p->key, p->value);
            passed++;
        } else {
            snprintf(action, sizeof(action), "FAIL: %s (expected %s)", p->key, p->value);
        }
        aegis_result_add_action(&res, action);
    }

    char msg[128];
    snprintf(msg, sizeof(msg), "sysctl: %d/%d parameters compliant", passed, total);
    free(res.message);
    res.message = strdup(msg);

    if (passed == total) {
        res.status = AEGIS_OK;
    } else if (passed > total / 2) {
        res.status = AEGIS_WARN;
    } else {
        res.status = AEGIS_FAIL;
    }
    return res;
}
