#define _POSIX_C_SOURCE 200809L
#include <aegis/modules/usbguard.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

aegis_result_t aegis_usbguard_apply(const void *config, aegis_executor_t *exec) {
    const aegis_usbguard_config_t *cfg = config;
    if (!cfg || !cfg->enabled)
        return aegis_result_skip("usbguard: disabled");

    aegis_result_t res = aegis_result_ok("usbguard: applied");

    /* Install usbguard */
    const char *install[] = {"pacman", "-S", "--noconfirm", "--needed", "usbguard", NULL};
    aegis_exec_result_t r = exec->execute_sudo(install, exec->ctx);
    if (r.exit_code != 0) {
        aegis_result_free(&res);
        aegis_exec_result_free(&r);
        return aegis_result_fail("usbguard: pacman -S failed");
    }
    aegis_exec_result_free(&r);
    aegis_result_add_action(&res, "Ensured usbguard package installed");

    /* Generate initial policy */
    const char *genpol[] = {"usbguard", "generate-policy", NULL};
    r = exec->execute_sudo(genpol, exec->ctx);
    const char *policy_content = (r.stdout_buf && r.stdout_buf[0]) ? r.stdout_buf : "# generated by aegis\n";
    if (exec->write_file("/etc/usbguard/rules.conf", policy_content, true, exec->ctx) != 0) {
        aegis_result_free(&res);
        aegis_exec_result_free(&r);
        return aegis_result_fail("usbguard: failed to write /etc/usbguard/rules.conf");
    }
    aegis_exec_result_free(&r);
    aegis_result_add_action(&res, "Generated and wrote /etc/usbguard/rules.conf");

    /* Set ImplicitPolicyTarget in daemon config */
    const char *policy = (cfg->default_policy && strcmp(cfg->default_policy, "allow") == 0)
                         ? "allow" : "block";
    char daemon_conf[512];
    snprintf(daemon_conf, sizeof(daemon_conf),
             "# Generated by aegis\n"
             "ImplicitPolicyTarget=%s\n"
             "PresentDevicePolicy=apply-policy\n"
             "PresentControllerPolicy=keep\n"
             "InsertedDevicePolicy=apply-policy\n"
             "RestoreControllerDeviceState=false\n"
             "DeviceManagerBackend=uevent\n"
             "IPCAllowedUsers=root\n"
             "IPCAllowedGroups=wheel\n"
             "IPCAccessControlFiles=/etc/usbguard/IPCAccessControl.d/\n",
             policy);
    if (exec->write_file("/etc/usbguard/usbguard-daemon.conf", daemon_conf, true, exec->ctx) != 0) {
        aegis_result_free(&res);
        return aegis_result_fail("usbguard: failed to write /etc/usbguard/usbguard-daemon.conf");
    }
    aegis_result_add_action(&res, "Configured ImplicitPolicyTarget in usbguard-daemon.conf");

    /* Enable service */
    const char *enable[] = {"systemctl", "enable", "--now", "usbguard", NULL};
    r = exec->execute_sudo(enable, exec->ctx);
    if (r.exit_code != 0) {
        aegis_result_free(&res);
        aegis_exec_result_free(&r);
        return aegis_result_fail("usbguard: systemctl enable usbguard failed");
    }
    aegis_exec_result_free(&r);
    aegis_result_add_action(&res, "Enabled usbguard service");

    char msg[128];
    snprintf(msg, sizeof(msg), "usbguard: applied with %s policy", policy);
    free(res.message);
    res.message = strdup(msg);
    return res;
}

aegis_result_t aegis_usbguard_status(aegis_executor_t *exec) {
    const char *argv[] = {"systemctl", "is-active", "usbguard", NULL};
    aegis_exec_result_t r = exec->execute(argv, exec->ctx);
    bool active = (r.exit_code == 0);
    aegis_exec_result_free(&r);

    bool rules_exist = exec->file_exists("/etc/usbguard/rules.conf", exec->ctx);

    char msg[128];
    snprintf(msg, sizeof(msg), "usbguard: service=%s rules=%s",
             active ? "active" : "inactive", rules_exist ? "present" : "missing");
    if (active && rules_exist) return aegis_result_ok(msg);
    if (active || rules_exist) return aegis_result_warn(msg);
    return aegis_result_fail(msg);
}

aegis_result_t aegis_usbguard_verify(aegis_executor_t *exec) {
    return aegis_usbguard_status(exec);
}
