#define _POSIX_C_SOURCE 200809L
#include <aegis/modules/usbguard.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define USBGUARD_CONV_DIR "/etc/aegis/rules.d/usbguard"
#define USBGUARD_RULES    "/etc/usbguard/rules.conf"

/* Append any *.rules files from the convention directory to rules.conf */
static void apply_convention_dir_usbguard(aegis_executor_t *exec, aegis_result_t *res) {
    const char *ls_argv[] = {"ls", USBGUARD_CONV_DIR, NULL};
    aegis_exec_result_t r = exec->execute(ls_argv, exec->ctx);
    if (r.exit_code != 0 || !r.stdout_buf || !r.stdout_buf[0]) {
        aegis_exec_result_free(&r);
        return; /* directory missing or empty — not an error */
    }

    /* Parse newline-separated filenames, apply only *.rules */
    char *listing = strdup(r.stdout_buf);
    aegis_exec_result_free(&r);
    if (!listing) return;

    /* Read current rules.conf to append to */
    char *current = exec->read_file(USBGUARD_RULES, exec->ctx);
    size_t cur_len = current ? strlen(current) : 0;

    char *tok = strtok(listing, "\n");
    while (tok) {
        /* Only process *.rules files */
        size_t flen = strlen(tok);
        if (flen > 6 && strcmp(tok + flen - 6, ".rules") == 0) {
            char path[512];
            snprintf(path, sizeof(path), "%s/%s", USBGUARD_CONV_DIR, tok);
            char *extra = exec->read_file(path, exec->ctx);
            if (extra) {
                size_t extra_len = strlen(extra);
                char *merged = malloc(cur_len + extra_len + 2);
                if (merged) {
                    if (current) memcpy(merged, current, cur_len);
                    merged[cur_len] = '\n';
                    memcpy(merged + cur_len + 1, extra, extra_len + 1);
                    free(current);
                    current = merged;
                    cur_len = cur_len + 1 + extra_len;
                }
                free(extra);
                char action[600];
                snprintf(action, sizeof(action),
                         "Appended convention rules from %s to " USBGUARD_RULES, path);
                aegis_result_add_action(res, action);
            }
        }
        tok = strtok(NULL, "\n");
    }
    free(listing);

    if (current) {
        exec->write_file(USBGUARD_RULES, current, true, exec->ctx);
        free(current);
    }
}

aegis_result_t aegis_usbguard_apply(const void *config, aegis_executor_t *exec) {
    const aegis_usbguard_config_t *cfg = config;
    if (!cfg || !cfg->enabled)
        return aegis_result_skip("usbguard: disabled");

    aegis_result_t res = aegis_result_ok("usbguard: applied");

    /* Install usbguard */
    const char *install[] = {"pacman", "-S", "--noconfirm", "--needed", "usbguard", NULL};
    aegis_exec_result_t r = exec->execute_sudo(install, exec->ctx);
    if (r.exit_code != 0) {
        aegis_result_free(&res);
        aegis_exec_result_free(&r);
        return aegis_result_fail("usbguard: pacman -S failed");
    }
    aegis_exec_result_free(&r);
    aegis_result_add_action(&res, "Ensured usbguard package installed");

    /* Generate initial policy */
    const char *genpol[] = {"usbguard", "generate-policy", NULL};
    r = exec->execute_sudo(genpol, exec->ctx);
    const char *policy_content = (r.stdout_buf && r.stdout_buf[0]) ? r.stdout_buf : "# generated by aegis\n";
    if (exec->write_file("/etc/usbguard/rules.conf", policy_content, true, exec->ctx) != 0) {
        aegis_result_free(&res);
        aegis_exec_result_free(&r);
        return aegis_result_fail("usbguard: failed to write /etc/usbguard/rules.conf");
    }
    aegis_exec_result_free(&r);
    aegis_result_add_action(&res, "Generated and wrote /etc/usbguard/rules.conf");

    /* Append any custom rules from convention directory */
    apply_convention_dir_usbguard(exec, &res);

    /* Set ImplicitPolicyTarget in daemon config */
    const char *policy = (cfg->default_policy && strcmp(cfg->default_policy, "allow") == 0)
                         ? "allow" : "block";
    char daemon_conf[512];
    snprintf(daemon_conf, sizeof(daemon_conf),
             "# Generated by aegis\n"
             "ImplicitPolicyTarget=%s\n"
             "PresentDevicePolicy=apply-policy\n"
             "PresentControllerPolicy=keep\n"
             "InsertedDevicePolicy=apply-policy\n"
             "RestoreControllerDeviceState=false\n"
             "DeviceManagerBackend=uevent\n"
             "IPCAllowedUsers=root\n"
             "IPCAllowedGroups=wheel\n"
             "IPCAccessControlFiles=/etc/usbguard/IPCAccessControl.d/\n",
             policy);
    if (exec->write_file("/etc/usbguard/usbguard-daemon.conf", daemon_conf, true, exec->ctx) != 0) {
        aegis_result_free(&res);
        return aegis_result_fail("usbguard: failed to write /etc/usbguard/usbguard-daemon.conf");
    }
    aegis_result_add_action(&res, "Configured ImplicitPolicyTarget in usbguard-daemon.conf");

    /* Enable service */
    const char *enable[] = {"systemctl", "enable", "--now", "usbguard", NULL};
    r = exec->execute_sudo(enable, exec->ctx);
    if (r.exit_code != 0) {
        aegis_result_free(&res);
        aegis_exec_result_free(&r);
        return aegis_result_fail("usbguard: systemctl enable usbguard failed");
    }
    aegis_exec_result_free(&r);
    aegis_result_add_action(&res, "Enabled usbguard service");

    char msg[128];
    snprintf(msg, sizeof(msg), "usbguard: applied with %s policy", policy);
    free(res.message);
    res.message = strdup(msg);
    return res;
}

aegis_result_t aegis_usbguard_status(aegis_executor_t *exec) {
    const char *argv[] = {"systemctl", "is-active", "usbguard", NULL};
    aegis_exec_result_t r = exec->execute(argv, exec->ctx);
    bool active = (r.exit_code == 0);
    aegis_exec_result_free(&r);

    bool rules_exist = exec->file_exists("/etc/usbguard/rules.conf", exec->ctx);

    char msg[128];
    snprintf(msg, sizeof(msg), "usbguard: service=%s rules=%s",
             active ? "active" : "inactive", rules_exist ? "present" : "missing");
    if (active && rules_exist) return aegis_result_ok(msg);
    if (active || rules_exist) return aegis_result_warn(msg);
    return aegis_result_fail(msg);
}

aegis_result_t aegis_usbguard_verify(aegis_executor_t *exec) {
    /* Per-item compliance: service active, config files present */
    aegis_result_t res = aegis_result_ok("usbguard: all checks passed");
    int total = 0, passed = 0;

    /* Check 1: service is active */
    total++;
    const char *svc_argv[] = {"systemctl", "is-active", "usbguard", NULL};
    aegis_exec_result_t r = exec->execute(svc_argv, exec->ctx);
    bool active = (r.exit_code == 0);
    aegis_exec_result_free(&r);
    aegis_result_add_action(&res, active
        ? "PASS: usbguard service is active"
        : "FAIL: usbguard service is not active");
    if (active) passed++;

    /* Check 2: rules.conf present */
    total++;
    bool rules_exist = exec->file_exists("/etc/usbguard/rules.conf", exec->ctx);
    aegis_result_add_action(&res, rules_exist
        ? "PASS: /etc/usbguard/rules.conf present"
        : "FAIL: /etc/usbguard/rules.conf missing");
    if (rules_exist) passed++;

    /* Check 3: daemon config present */
    total++;
    bool daemon_conf_exists = exec->file_exists("/etc/usbguard/usbguard-daemon.conf", exec->ctx);
    aegis_result_add_action(&res, daemon_conf_exists
        ? "PASS: /etc/usbguard/usbguard-daemon.conf present"
        : "FAIL: /etc/usbguard/usbguard-daemon.conf missing");
    if (daemon_conf_exists) passed++;

    char msg[128];
    snprintf(msg, sizeof(msg), "usbguard: %d/%d checks passed", passed, total);
    free(res.message);
    res.message = strdup(msg);

    if (passed == total) {
        res.status = AEGIS_OK;
    } else if (passed > total / 2) {
        res.status = AEGIS_WARN;
    } else {
        res.status = AEGIS_FAIL;
    }
    return res;
}
