# Generated by Django 5.2.17 on 2026-09-08

import uuid

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_id", models.CharField(db_index=True, max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[("foundation.probe", "Foundation probe")], max_length=64
                    ),
                ),
                ("request_hash", models.BinaryField(max_length=32, unique=True)),
                ("intent", models.JSONField()),
                ("authorization_snapshot", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_role",
                    models.CharField(
                        choices=[
                            ("operations", "Operations"),
                            ("indexer", "Indexer"),
                            ("media", "Media"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("foundation.probe", "Foundation probe")], max_length=64
                    ),
                ),
                ("payload", models.JSONField()),
                ("priority", models.SmallIntegerField(default=0)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("retry_wait", "Retry wait"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("available_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("attempt_token", models.PositiveBigIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("lease_owner", models.CharField(max_length=36, null=True)),
                ("lease_expires_at", models.DateTimeField(null=True)),
                ("safe_error_code", models.CharField(max_length=64, null=True)),
                ("safe_error_detail", models.CharField(max_length=512, null=True)),
                ("result", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="operations.operation",
                    ),
                ),
            ],
            options={
                "base_manager_name": "objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="WorkerHeartbeat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("operations", "Operations"),
                            ("indexer", "Indexer"),
                            ("media", "Media"),
                        ],
                        max_length=16,
                    ),
                ),
                ("worker_id", models.CharField(max_length=36)),
                ("release_id", models.CharField(max_length=96)),
                ("schema_identity", models.CharField(max_length=96)),
                ("manifest_identity", models.CharField(max_length=64)),
                ("last_seen_at", models.DateTimeField()),
                ("current_job_id", models.UUIDField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("idle", "Idle"), ("running", "Running"), ("stopping", "Stopping")],
                        max_length=16,
                    ),
                ),
                ("metrics", models.JSONField(default=dict)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("role", "worker_id"),
                        name="operations_heartbeat_role_worker_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("role__in", ["operations", "indexer", "media"])),
                        name="operations_heartbeat_role_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["idle", "running", "stopping"])),
                        name="operations_heartbeat_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "worker_id__regex",
                                "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
                            )
                        ),
                        name="operations_heartbeat_worker_uuid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "release_id__regex",
                                "^[A-Za-z0-9][A-Za-z0-9._:+-]{0,95}$",
                            )
                        ),
                        name="operations_heartbeat_release_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "schema_identity__regex",
                                "^[A-Za-z0-9][A-Za-z0-9._:+-]{0,95}$",
                            )
                        ),
                        name="operations_heartbeat_schema_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("manifest_identity", "unconfigured:v1"),
                            ("manifest_identity__regex", "^[0-9a-f]{64}$"),
                            _connector="OR",
                        ),
                        name="operations_heartbeat_manifest_valid",
                    ),
                    models.CheckConstraint(
                        condition=django.db.models.expressions.RawSQL(
                            "jsonb_typeof(metrics) = 'object'",
                            (),
                            output_field=models.BooleanField(),
                        ),
                        name="operations_heartbeat_metrics_object",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="operation",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["foundation.probe"])),
                name="operations_operation_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="operation",
            constraint=models.CheckConstraint(
                condition=models.Q(("request_id__regex", "^[A-Za-z0-9_-]{8,64}$")),
                name="operations_operation_request_id_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="operation",
            constraint=models.CheckConstraint(
                condition=django.db.models.expressions.RawSQL(
                    "octet_length(request_hash) = 32",
                    (),
                    output_field=models.BooleanField(),
                ),
                name="operations_operation_hash_32_bytes",
            ),
        ),
        migrations.AddConstraint(
            model_name="operation",
            constraint=models.CheckConstraint(
                condition=django.db.models.expressions.RawSQL(
                    "jsonb_typeof(intent) = 'object' AND "
                    "jsonb_typeof(authorization_snapshot) = 'object'",
                    (),
                    output_field=models.BooleanField(),
                ),
                name="operations_operation_json_objects",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["target_role", "state", "-priority", "available_at", "id"],
                name="operations_job_claim_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["lease_expires_at"], name="operations_job_lease_idx"),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                fields=("operation", "target_role"),
                name="operations_job_operation_role_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_role__in", ["operations", "indexer", "media"])),
                name="operations_job_role_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["foundation.probe"])),
                name="operations_job_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["queued", "running", "retry_wait", "succeeded", "failed"])
                ),
                name="operations_job_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__gte", -32768), ("priority__lte", 32767)),
                name="operations_job_priority_bounded",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_attempts__gte", 1), ("max_attempts__lte", 100)),
                name="operations_job_max_attempts_bounded",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("attempts__gte", 0), ("attempts__lte", models.F("max_attempts"))
                ),
                name="operations_job_attempts_bounded",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_token__gte", models.F("attempts"))),
                name="operations_job_attempt_token_monotonic",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("lease_expires_at__isnull", False),
                        ("lease_owner__isnull", False),
                        ("state", "running"),
                    ),
                    models.Q(
                        models.Q(("state", "running"), _negated=True),
                        ("lease_expires_at__isnull", True),
                        ("lease_owner__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="operations_job_running_lease_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lease_owner__isnull", True),
                    (
                        "lease_owner__regex",
                        "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
                    ),
                    _connector="OR",
                ),
                name="operations_job_lease_owner_uuid",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("safe_error_code__isnull", True),
                    (
                        "safe_error_code__in",
                        [
                            "authorization_stale",
                            "attempts_exhausted",
                            "handler_failed",
                            "retryable_failure",
                        ],
                    ),
                    _connector="OR",
                ),
                name="operations_job_error_code_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("safe_error_code__isnull", False),
                        ("safe_error_detail__isnull", False),
                        ("state__in", ("failed", "retry_wait")),
                    ),
                    models.Q(
                        ("safe_error_code__isnull", True),
                        ("safe_error_detail__isnull", True),
                        ("state__in", ("queued", "running", "succeeded")),
                    ),
                    _connector="OR",
                ),
                name="operations_job_error_state_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("result__isnull", False), ("state", "succeeded")),
                    models.Q(
                        models.Q(("state", "succeeded"), _negated=True),
                        ("result__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="operations_job_result_state_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=django.db.models.expressions.RawSQL(
                    "jsonb_typeof(payload) = 'object' AND "
                    "(result IS NULL OR jsonb_typeof(result) = 'object')",
                    (),
                    output_field=models.BooleanField(),
                ),
                name="operations_job_json_objects",
            ),
        ),
    ]
