# Generated by Django 5.2.17 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="request_hash",
            field=models.BinaryField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name="operation",
            constraint=models.UniqueConstraint(
                fields=("actor", "request_id"),
                name="operations_operation_actor_request_uniq",
            ),
        ),
    ]
