# Generated by Django 5.2.17 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0002_operation_idempotency"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workerheartbeat",
            index=models.Index(
                fields=["role", "last_seen_at"],
                name="operations_hb_role_seen_idx",
            ),
        ),
    ]
