# Generated by Django 5.2.17 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0003_workerheartbeat_role_seen_index"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="job",
            name="operations_job_error_code_valid",
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("safe_error_code__isnull", True),
                    (
                        "safe_error_code__in",
                        [
                            "authorization_stale",
                            "attempts_exhausted",
                            "handler_failed",
                            "retryable_failure",
                            "claim_relinquished",
                        ],
                    ),
                    _connector="OR",
                ),
                name="operations_job_error_code_valid",
            ),
        ),
    ]
