# Generated by Django 5.2.17 on 2026-09-09

from django.db import migrations, models

PROMOTE_UNAMBIGUOUS = """
UPDATE operations_operation AS candidate
SET idempotency_namespace = 'v1'
WHERE NOT EXISTS (
    SELECT 1
    FROM operations_operation AS sibling
    WHERE sibling.actor_id IS NOT DISTINCT FROM candidate.actor_id
      AND sibling.request_id = candidate.request_id
      AND sibling.id <> candidate.id
)
"""


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0004_job_claim_relinquished_error"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE operations_operation DROP CONSTRAINT IF EXISTS "
                "operations_operation_actor_request_uniq"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="operation",
            name="idempotency_namespace",
            field=models.CharField(editable=False, max_length=16, null=True),
        ),
        migrations.RunSQL(
            sql=PROMOTE_UNAMBIGUOUS,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="operation",
            name="idempotency_namespace",
            field=models.CharField(default="v1", editable=False, max_length=16, null=True),
        ),
        migrations.AddConstraint(
            model_name="operation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("idempotency_namespace__isnull", True),
                    ("idempotency_namespace", "v1"),
                    _connector="OR",
                ),
                name="operations_operation_idempotency_namespace_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="operation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_namespace", "v1")),
                fields=("actor", "request_id"),
                name="operations_operation_actor_request_v1_uniq",
            ),
        ),
    ]
