# Generated by Django 5.2.17 on 2026-09-14 15:30

import uuid

import django.db.models.deletion
import django.db.models.lookups
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('roots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexDeployment',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('epoch', models.PositiveBigIntegerField(default=1, editable=False)),
                ('manifest_identity', models.CharField(max_length=64)),
                ('slot_ids', models.JSONField(default=list)),
                ('interval_seconds', models.PositiveIntegerField()),
                ('idle_timeout_seconds', models.PositiveSmallIntegerField()),
                ('batch_records', models.PositiveSmallIntegerField()),
                ('readers', models.PositiveSmallIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='indexing_deploy_singleton'), models.CheckConstraint(condition=models.Q(('epoch__gte', 1)), name='indexing_deploy_epoch_positive'), models.CheckConstraint(condition=models.Q(('interval_seconds__gte', 60), ('interval_seconds__lte', 604800), ('idle_timeout_seconds__gte', 30), ('idle_timeout_seconds__lte', 3600), ('batch_records__gte', 100), ('batch_records__lte', 2000), ('readers__gte', 1), ('readers__lte', 4)), name='indexing_deploy_policy_bounded'), models.CheckConstraint(condition=models.Q(('manifest_identity', 'unconfigured:v1'), ('manifest_identity__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='indexing_deploy_manifest_valid'), models.CheckConstraint(condition=models.Q(django.db.models.lookups.Exact(models.Func('slot_ids', function='jsonb_typeof', output_field=models.CharField()), models.Value('array')), django.db.models.lookups.LessThanOrEqual(models.Func('slot_ids', function='jsonb_array_length', output_field=models.IntegerField()), 128)), name='indexing_deploy_slots_bounded')],
            },
        ),
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('binding_epoch', models.PositiveBigIntegerField()),
                ('policy_epoch', models.PositiveBigIntegerField()),
                ('root_epoch', models.PositiveBigIntegerField()),
                ('manifest_identity', models.CharField(max_length=64)),
                ('generation', models.PositiveBigIntegerField()),
                ('start_epoch', models.PositiveBigIntegerField()),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('complete', 'Complete'), ('degraded', 'Degraded'), ('fenced', 'Fenced')], max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('settled_at', models.DateTimeField(null=True)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_runs', to='roots.root')),
            ],
        ),
        migrations.CreateModel(
            name='ScanRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_request_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_requests', to=settings.AUTH_USER_MODEL)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_requests', to='roots.root')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='indexing.scanrun')),
            ],
        ),
        migrations.CreateModel(
            name='RootIndexState',
            fields=[
                ('root', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='index_state', serialize=False, to='roots.root')),
                ('binding_epoch', models.PositiveBigIntegerField()),
                ('policy_epoch', models.PositiveBigIntegerField()),
                ('reconciliation_epoch', models.PositiveBigIntegerField(default=0)),
                ('next_generation', models.PositiveBigIntegerField(default=1)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('rescan_requested', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('not_indexed', 'Not Indexed'), ('queued', 'Queued'), ('scanning', 'Scanning'), ('ready', 'Ready'), ('degraded', 'Degraded'), ('unavailable', 'Unavailable')], default='not_indexed', max_length=16)),
                ('observed_entries', models.PositiveBigIntegerField(default=0)),
                ('completed_directories', models.PositiveBigIntegerField(default=0)),
                ('degraded_directories', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_completed_at', models.DateTimeField(null=True)),
                ('active_run', models.OneToOneField(db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_for_root_state', to='indexing.scanrun')),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_revision', models.PositiveBigIntegerField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('reading', 'Reading'), ('finalizing', 'Finalizing'), ('complete', 'Complete'), ('degraded', 'Degraded')], default='pending', max_length=16)),
                ('attempt', models.PositiveIntegerField(default=0)),
                ('lease_owner', models.UUIDField(null=True)),
                ('lease_expires_at', models.DateTimeField(null=True)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_batch_sequence', models.PositiveIntegerField(default=0)),
                ('observed_count', models.PositiveBigIntegerField(default=0)),
                ('eof_identity', models.JSONField(null=True)),
                ('error_code', models.CharField(max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directory_work', to='catalog.catalogentry')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directory_work', to='indexing.scanrun')),
            ],
        ),
        migrations.AddConstraint(
            model_name='scanrun',
            constraint=models.UniqueConstraint(fields=('root', 'id'), name='indexing_run_root_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scanrun',
            constraint=models.UniqueConstraint(fields=('root', 'generation'), name='indexing_run_root_generation_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scanrun',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ('queued', 'running'))), fields=('root',), name='indexing_one_active_run_per_root'),
        ),
        migrations.AddConstraint(
            model_name='scanrun',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('queued', 'running', 'complete', 'degraded', 'fenced'))), name='indexing_run_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='scanrun',
            constraint=models.CheckConstraint(condition=models.Q(('manifest_identity', 'unconfigured:v1'), ('manifest_identity__regex', '^[0-9a-f]{64}$'), _connector='OR'), name='indexing_run_manifest_valid'),
        ),
        migrations.AddConstraint(
            model_name='scanrequest',
            constraint=models.UniqueConstraint(fields=('actor', 'client_request_id'), name='indexing_request_actor_client_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scanrequest',
            constraint=models.CheckConstraint(condition=models.Q(('client_request_id__regex', '^[A-Za-z0-9_-]{8,64}$')), name='indexing_request_id_valid'),
        ),
        migrations.AddConstraint(
            model_name='rootindexstate',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('not_indexed', 'queued', 'scanning', 'ready', 'degraded', 'unavailable'))), name='indexing_root_status_valid'),
        ),
        migrations.AddIndex(
            model_name='directorywork',
            index=models.Index(fields=['run', 'state', 'available_at', 'id'], name='indexing_work_claim_idx'),
        ),
        migrations.AddConstraint(
            model_name='directorywork',
            constraint=models.UniqueConstraint(fields=('run', 'directory'), name='indexing_work_run_directory_uniq'),
        ),
        migrations.AddConstraint(
            model_name='directorywork',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('pending', 'reading', 'finalizing', 'complete', 'degraded'))), name='indexing_work_state_valid'),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE indexing_rootindexstate
                    ADD CONSTRAINT indexing_active_run_same_root
                    FOREIGN KEY (root_id, active_run_id)
                    REFERENCES indexing_scanrun (root_id, id)
                    ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
                ALTER TABLE indexing_rootindexstate
                    DROP CONSTRAINT indexing_active_run_same_root;
            """,
        ),
    ]
